# Information for compile
exclude: ["Gemfile"]

baseurl:

# the base hostname & protocol for your site
url: "https://localhost:3000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Sera - OnePage Multi-Purpose Theme
# Website language
lang: en-US
# Header Title
header-title: Create the <strong>Impossible</strong>
# Header Tagline
headter-tagline: We Always

email: cyril.vandenberghe.pro@gmail.com

####################################
######  Global Social Links   ######
####################################
linkedin: "https://www.linkedin.com/in/vdbcyril"
github: "https://github.com/vdbcyril"

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar.jpg
  author-name: John Doe
  author-tagline: Blog Author
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.

#####################################
#############   About   #############
#####################################
about-title: Welcome to Sera
about-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#####################################
############  Portfolio  ############
#####################################
portfolio-title: Portfolio
portfolio-description: Maecenas tempus nec mi et placerat. Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis.

#
# Portfolio Grid
#
portfolio-categories: [R, Analysis, Machine Learning, Python]
portfolio:
  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Analysis, R language]
    image: img-01.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [R language, Machine Learning, Analysis]
    image: img-02.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [R language, Machine Learning, Python]
    image: img-03.jpg
    url: "#"

#####################################
############# Our Blog ##############
#####################################
blog-title: Our Blog
blog-description: Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#####################################
############   Contact   ############
#####################################
contact-title: Contact Me

#####################################
#############   Footer   ############
#####################################
footer-copyright-text: Cyril Vandenberghe
footer-copyright-year: 2019
