# Information for compile
exclude: ["Gemfile"]

baseurl:

# the base hostname & protocol for your site
url: "https://localhost:3000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Cyril Vandenberghe - Portfolio
# Website language
lang: en-US
# Header Title
header-title: I am a Data Scientist
# Header Tagline
headter-tagline: Hello, my name is Cyril

email: cyril.vandenberghe.pro@gmail.com

####################################
######  Global Social Links   ######
####################################
linkedin: "https://www.linkedin.com/in/vdbcyril"
github: "https://github.com/vdbcyril"

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar.jpg
  author-name: Cyril Vandenberghe
  author-tagline: Data Scientist
  author-info: I like to write posts about data science

#####################################
#############   About   #############
#####################################
about-title: Welcome to my website
about-description: You can read my blog and find some tutorials and notes about data science. You can also have a look at my projects.

#####################################
############  Portfolio  ############
#####################################
portfolio-title: Portfolio
portfolio-description: My personal projects involving data analysis and Machine Learning.

#
# Portfolio Grid
#
portfolio-categories: [R, Python, Analysis, Machine Learning, Deep Learning]
portfolio:
  # Portfolio Item
  - title: Hopper Airports (Dashboard)
    categories: [R, Analysis]
    image: airport.jpg
    alt: "Photo by Ken Yam on Unsplash"
    url: "https://vdbcyril.shinyapps.io/hopper-dashboard/"
  # Portfolio Item
  - title: Hopper Airports (Markdown)
    categories: [R, Analysis]
    image: passenger.jpg
    alt: "Photo by Max Delsid on Unsplash"
    url: "https://cyrilvandenberghe.com/hopper.html"
  # Portfolio Item
  - title: Criminal Acts in Montreal
    categories: [R, Analysis]
    image: handcuff.jpg
    alt: "Photo by Bill Oxford on Unsplash"
    url: "https://vdbcyril.shinyapps.io/incidents-montreal-en"
  # Portfolio Item
  - title: "Datacamp Projects"
    categories: [R, Analysis, Machine Learning, Python, Deep Learning]
    image: datacamp.png
    alt: "Datacamp Logo"
    url: "https://github.com/vdbcyril/datacamp-projects"

#####################################
############# Blog ##############
#####################################
blog-title: My Blog
blog-description: I write tutorials and notes about data science, enjoy !

#####################################
############   Contact   ############
#####################################
contact-title: Contact Me

#####################################
#############   Footer   ############
#####################################
footer-copyright-text: Cyril Vandenberghe
footer-copyright-year: 2019
